In [2]:
import torch 

x=torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(x)
print(x.ndim)
print(x.shape)
print(x.device)

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
cpu


In [3]:
torch.cuda.is_available()

False

In [4]:
a=torch.randn(4,2)
print(a)
b=torch.rand(4,2)
print(b)

tensor([[ 0.0831,  1.0113],
        [ 0.3383,  0.8008],
        [ 1.6823,  1.0301],
        [-1.6711, -1.3089]])
tensor([[0.3762, 0.5305],
        [0.2484, 0.3114],
        [0.3433, 0.5039],
        [0.1052, 0.9514]])


In [9]:
def myfunc(*size):
    print(size)
    print(type(size))

myfunc(2,3,4)
myfunc(4,5)
myfunc(5)

(2, 3, 4)
<class 'tuple'>
(4, 5)
<class 'tuple'>
(5,)
<class 'tuple'>
