In [22]:
%matplotlib inline
import torch 
import matplotlib.pyplot as plt

from torch import nn 



#X.shape (1000,2)
#y.shape(1000,1)

hidden_size=8
class XORModel(nn.Module):
    def __init__(self,input_dim,hidden_dim,output_dim):
        super().__init__()
        # self.params=a 
        # hidden_num=8
        #self.linear1=nn.Linear(torch.randn((2,hidden_size)))
        self.linear1=nn.Linear(input_dim,hidden_dim)
        self.relu1=nn.ReLU()
        self.linear2=nn.Linear(hidden_dim,output_dim) # nn.Linear(torch.rand((hidden_dim,1)))
        self.net=nn.Sequential(
            self.linear1,
            self.relu1,
            self.linear2,
        )



    def forward(self,X):
        #a
        y=  self.net(X)
        #logit 
        return y


input_dim=2
output_dim=1
hidden_dim=8

net=XORModel(input_dim,hidden_dim,output_dim)
X_test = torch.randn(32, 2)

output=net(X_test)
print(output.shape)
print("\n")


y=torch.randint(low=0,high=2,size=(32,1)).float()
print(y.shape)
for param in net.parameters():
    print(param.shape)

lr=0.01
optimizer=torch.optim.SGD(params=net.parameters(),lr=0.01)
# criterion=torch.nn.BCEWithLogitsLoss()
loss_fn=torch.nn.BCEWithLogitsLoss()
# loss_fn=criterion(logits,targets)

EPOCH_SIZE=100
print(net.linear1.weight.grad)
X=torch.randn(32,2)
y_hat=net(X)
print(y_hat.shape)
loss=loss_fn(y_hat,y)
print(loss)
print(loss.shape)


print(net.linear1.weight.grad)
loss.backward()
print(net.linear1.weight.grad)

print("weight shape:")
print(net.linear1.weight.shape)

print("grad shape:")
print(net.linear1.weight.grad.shape)

before=net.linear1.weight.detach().clone()
optimizer.step()
after = net.linear1.weight.detach().clone()
print(before)
print(after)
# loss_fn=torch.loss 
# optimizer=torch.optim.SGD(params=) #params怎么填
# net=XORModel()
# for i in EPOCH_SIZE:
#     loss.zero_grad()
#     y_hat=net(X)
#     loss= loss_fn(y_hat,y)
#     loss.backward()
#     optimizer.step()

#     net.eval()
#     with net.inference_model():


# for epoch in range(EPOCH_SIZE):
#     net.train()

#     optimizer.zero_grad()
#     y_hat=net.forward()
#     targets=x

#     loss=criterion(y_hat,targets)
#     loss.backward()

#     optimizer.step()


    





torch.Size([32, 1])


torch.Size([32, 1])
torch.Size([8, 2])
torch.Size([8])
torch.Size([1, 8])
torch.Size([1])
None
torch.Size([32, 1])
tensor(0.6832, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
torch.Size([])
None
tensor([[-0.0001, -0.0012],
        [ 0.0000,  0.0000],
        [ 0.0004,  0.0010],
        [-0.0040, -0.0091],
        [-0.0182, -0.0205],
        [ 0.0000,  0.0000],
        [-0.0002, -0.0119],
        [ 0.0021, -0.0194]])
weight shape:
torch.Size([8, 2])
grad shape:
torch.Size([8, 2])
tensor([[ 0.3876,  0.1935],
        [-0.2865, -0.0326],
        [-0.3654, -0.2321],
        [-0.3317, -0.2485],
        [-0.3650,  0.3161],
        [-0.3029, -0.0923],
        [ 0.1553, -0.6043],
        [ 0.6048, -0.6726]])
tensor([[ 0.3876,  0.1935],
        [-0.2865, -0.0326],
        [-0.3654, -0.2321],
        [-0.3317, -0.2484],
        [-0.3648,  0.3163],
        [-0.3029, -0.0923],
        [ 0.1553, -0.6042],
        [ 0.6048, -0.6724]])
